name: pokedex_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  design_system:
    path: ./design_system
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  dio: ^5.3.0
  flutter_modular: ^5.0.3
  cached_network_image: ^3.2.3
  sliding_up_panel: ^2.0.0+1
  flutter_svg: ^2.0.7
  graphql: ^5.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # mockito: ^5.4.2
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
